### ISSUE TITLE
Home assistant add-on crash

### ISSUE THREAD

**Issue by CeccoCQ** [andrea-mattioli/bticino_X8000_rest_api#3]
Hi Andrea,
thanks for your great work!

After some days of use, I've encountered this error when I update Home assistant to latest version:

```
Traceback (most recent call last):
  File "bticino.py", line 516, in <module>
    schedule_update_token()
  File "bticino.py", line 512, in schedule_update_token
    f_refresh_token()
  File "bticino.py", line 199, in f_refresh_token
    if not check_empty_item("refresh_token"):
  File "bticino.py", line 77, in check_empty_item
    json_object=get_json()
  File "bticino.py", line 85, in get_json
    json_object = json.load(a_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4386 (char 4385)
Traceback (most recent call last):
  File "mqtt.py", line 5, in <module>
    from bticino import send_thermostat_cmd, load_api_config_arg
  File "/hassio_bticino_smarter/bticino.py", line 516, in <module>
    schedule_update_token()
  File "/hassio_bticino_smarter/bticino.py", line 512, in schedule_update_token
    f_refresh_token()
  File "/hassio_bticino_smarter/bticino.py", line 199, in f_refresh_token
    if not check_empty_item("refresh_token"):
  File "/hassio_bticino_smarter/bticino.py", line 77, in check_empty_item
    json_object=get_json()
  File "/hassio_bticino_smarter/bticino.py", line 85, in get_json
    json_object = json.load(a_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4386 (char 4385)
[cmd] /hassio_bticino_smarter/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
2020/05/22 15:33:38 [notice] 288#288: signal 1 (SIGHUP) received from 333, reconfiguring
2020/05/22 15:33:38 [notice] 294#294: signal 1 (SIGHUP) received from 333, ignoring
2020/05/22 15:33:38 [info] 294#294: epoll_wait() failed (4: Interrupted system call)
2020/05/22 15:33:38 [notice] 288#288: reconfiguring
```

I tried to navigate to link ...:558 but all seems killed.
What's wrong in your opinion?

Thanks

**Comment by andrea-mattioli** [comment]
Hi, (update to the last add-on version 0.3) then try to remove the persistent config directory locate in /config.
you can do it from ssh add-on running command:
rm -rf /root/config/.bticino_smarter
or trought samba as you like!
then try to rebuild the add-on and check if your hassio is reachble on 5588 if it works then you must  click on "get your code"
A.

**Comment by CeccoCQ** [comment]
Hi,
it's ok, works fine! Thanks.

**Comment by andrea-mattioli** [comment]
Ok Good!

**Comment by umby63** [comment]
Hi Andrea, when I try to use get-code, I receive a window where I allow the access , but then I receive a message "internal error server", inside register queue I see an error callback "File "/hassio_bticino_smarter/bticino.py", line 299, in get_plants"
