### ISSUE TITLE
Exception on /callback [GET]

### ISSUE THREAD

**Issue by HSMarzio** [andrea-mattioli/bticino_X8000_rest_api#9]
Hi Andrea,
i'm using Bticino X8000 v2 but, when i try to allow my app permissions i receive :

**Internal Server Error**
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

below the add-on logs:
7.2.224.140 - - [13/Dec/2022 10:40:10] "GET / HTTP/1.1" 200 -
[2022-12-13 10:40:15,014] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 299, in get_plants
    plants = json.loads(response.text)['plants']
KeyError: 'plants'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/hassio_bticino_smarter/bticino.py", line 744, in callback
    my_plants=get_plants(access_token)
  File "/hassio_bticino_smarter/bticino.py", line 307, in get_plants
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'KeyError' object has no attribute 'errno'

do you have some suggestion ?

**Comment by andrea-mattioli** [comment]
Did you enable third party access from the original app?
Which model of smarther are you trying to configure?

**Comment by HSMarzio** [comment]
Hi Andrea, thank you for your time. I can close the issue because i've just solved.
I was not able to get the code because i was logging to lengrad using my developper account instead of the account linked to the thermostats.

**Comment by andrea-mattioli** [comment]
ok thx
